version: '3.7'

services:
  neo4j:
    image: neo4j-apoc
    restart: unless-stopped
    volumes:
      - experiment-kggi-data:/var/lib/neo4j/data
      - experiment-kggi-config:/var/lib/neo4j/conf
    build:
      context: .
      dockerfile: DockerfileNeo4J
    networks:
    - internal
    ports:
    - "7687:7687"
    - "7474:7474"
    environment:
      NEO4J_AUTH: neo4j/spring

volumes:
  experiment-kggi-data:
  experiment-kggi-config:

networks:
  internal:
    driver: bridge

