/*
 * Copyright (c) 2022 the original author or authors.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 */

package at.fh.hagenberg.machinelearning.analytics.graph.nodes;

import org.neo4j.ogm.annotation.EndNode;
import org.neo4j.ogm.annotation.Id;
import org.neo4j.ogm.annotation.RelationshipEntity;
import org.neo4j.ogm.annotation.StartNode;

import java.io.Serializable;

/**
 * @author Oliver Krauss on 08.10.2019
 */
@RelationshipEntity(type = "CHILD")
public class OrderedRelationship implements Comparable<OrderedRelationship>, Serializable {

    /**
     * Id generated by database
     */
    @Id
    private Long id;

    /**
     * Name of filed that node occured in
     */
    private String field;

    /**
     * Order that the child nodes occured in the field (if it was a collection)
     */
    private int order;

    @StartNode
    NodeWrapper parent;

    @EndNode
    NodeWrapper child;

    public OrderedRelationship() {
    }

    public OrderedRelationship(NodeWrapper parent, NodeWrapper child, String field, int order) {
        this.field = field;
        this.order = order;
        this.parent = parent;
        this.child = child;
    }

    @Override
    public int compareTo(OrderedRelationship o) {
        if (o == null) {
            // null is the smallest
            return 1;
        }

        int comp = 0;
        if (field == null) {
            if (o.getField() != null) {
                comp = -1;
            }
        } else {
            comp = field.compareTo(o.getField());
        }

        return comp == 0 ? Integer.compare(order, o.getOrder()) : comp;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getField() {
        return field;
    }

    public void setField(String field) {
        this.field = field;
    }

    public int getOrder() {
        return order;
    }

    public void setOrder(int order) {
        this.order = order;
    }

    public NodeWrapper getParent() {
        return parent;
    }

    public void setParent(NodeWrapper parent) {
        this.parent = parent;
    }

    public NodeWrapper getChild() {
        return child;
    }

    public void setChild(NodeWrapper child) {
        this.child = child;
    }
}
