/*
 * Copyright (c) 2022 the original author or authors.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 */

package at.fh.hagenberg.machinelearning.analytics.graph.nodes;

import at.fh.hagenberg.machinelearning.core.Solution;
import org.neo4j.ogm.annotation.*;

@RelationshipEntity(type = "POPULATION")
public class PopulationRelationship {

    /**
     * Id generated by database
     */
    @Id
    private Long id;

    private Long count;

    @StartNode
    StepNode step;

    @EndNode
    Solution solution;

    public PopulationRelationship() {
    }

    public PopulationRelationship(Long count, StepNode step, Solution solution) {
        this.count = count;
        this.step = step;
        this.solution = solution;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCount() {
        return count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    public StepNode getStep() {
        return step;
    }

    public void setStep(StepNode step) {
        this.step = step;
    }

    public Solution getSolution() {
        return solution;
    }

    public void setSolution(Solution solution) {
        this.solution = solution;
    }
}
