/*
 * Copyright (c) 2022 the original author or authors.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 */

package at.fh.hagenberg.aist.gce.optimization.test;

import at.fh.hagenberg.machinelearning.analytics.graph.nodes.NodeWrapper;
import at.fh.hagenberg.machinelearning.analytics.graph.nodes.OrderedRelationship;
import org.neo4j.ogm.annotation.EndNode;
import org.neo4j.ogm.annotation.Id;
import org.neo4j.ogm.annotation.RelationshipEntity;
import org.neo4j.ogm.annotation.StartNode;

import java.io.Serializable;

@RelationshipEntity(type = "TEST_INPUT")
public class OrderedTestInput implements Comparable<OrderedTestInput>, Serializable {


    /**
     * Id generated by database
     */
    @Id
    private Long id;

    /**
     * Order that the child nodes occured in the field (if it was a collection)
     */
    private int order;

    @StartNode
    TruffleOptimizationTest test;

    @EndNode
    TruffleTestValue input;

    public OrderedTestInput() {
    }

    public OrderedTestInput(TruffleOptimizationTest test, TruffleTestValue input, int order) {
        this.order = order;
        this.test = test;
        this.input = input;
    }

    @Override
    public int compareTo(OrderedTestInput o) {
        if (o == null) {
            // null is the smallest
            return 1;
        }

        return Integer.compare(order, o.getOrder());
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getOrder() {
        return order;
    }

    public void setOrder(int order) {
        this.order = order;
    }

    public TruffleOptimizationTest getTest() {
        return test;
    }

    public void setTest(TruffleOptimizationTest test) {
        this.test = test;
    }

    public TruffleTestValue getInput() {
        return input;
    }

    public void setInput(TruffleTestValue input) {
        this.input = input;
    }
}
